CREATE TABLE DEPENDENCY_RESULT_MAIN
(
NRUNID number,
TRUNTYPE varchar2(30),
OWNER varchar2(150),
OBJECT_NAME varchar2(150),
DSTARTDATE date,
DENDDATE date
)
/
CREATE TABLE DEPENDENCY_RESULT_SCHEMA
(
NRUNID number,
OWNER varchar2(150),
NOBJECTCOUNT number,
DSTARTDATE date,
DENDDATE date
)
/
CREATE TABLE DEPENDENCY_RESULT
(
NRUNID number,
OBJECT_NAME varchar2(150),
OWNER varchar2(150),
OPERATION VARCHAR2(50),
LINE number,
COLUMNNAME varchar2(200),
TABLEOWNER varchar2(100),
TABLENAME varchar2(200),
STATEMENT VARCHAR2(4000),
ISEXCEPTION number(1),
MULTIBLEASSIGNMENTEXIST number(1),
COMPLEXASSIGNMENTEXIST number(1),
STRINGCONCATENATIONEXIST number(1),
TABLENOTCATCHED number(1)
)
/
CREATE TABLE DEPENDENCY_RESULT_EXCEPTION
(
NRUNID number,
EXCEPTION_TYPE varchar2(150),
OWNER varchar2(150),
OBJECT_NAME varchar2(150),
ERR varchar2(4000)
)
/
CREATE TABLE DEPENDENCY_RESULT_EST
(
NRUNID NUMBER,
SCHEMA VARCHAR2(100),
EFFORT_1 NUMBER,
EFFORT_2 number
)
/
CREATE TABLE DEPENDENCY_RESULT_EST_DETAIL
(
NRUNID number,
SCHEMA varchar2(100),
PROC varchar2(100),
LOC NUMBER,
EFFORT_TYPE NUMBER,
ST_COUNT number,
SC_COUNT number,
SSC_COUNT number,
MT_COUNT number,
MC_COUNT number,
IT_COUNT number,
IC_COUNT number,
UT_COUNT number,
UC_COUNT number,
DT_COUNT number,
DC_COUNT number,
DCT_COUNT number,
DCC_COUNT number,
DST_COUNT number,
DSC_COUNT number,
MULEXT_COUNT number,
COMPLEX_ASS_COUNT number,
STRING_CON_COUNT number,
NOT_CATCHED_COUNT number
)
/
CREATE INDEX DEPENDENCY_RESULT_INX on DEPENDENCY_RESULT(OBJECT_NAME,NRUNID,ISEXCEPTION,OPERATION,COLUMNNAME);