/*****************************************

It is used to estimated refactoring efforts

It is necessary to update following variables

iRunId --> Run id can be found in DEPENDENCY_RESULT_MAIN table. It is equal 1 for first run.
iSchema --> Schema name to be effort estimated

*****************************************/
DECLARE

iRunId NUMBER:=1; 
iSchema varchar2(100):='?';

B1 number:=35; -- Balance Constant 1
B2 number:=70; -- Balance Constant 2
LC NUMBER:=10; -- LOC Constant

cursor C1 IS 
SELECT OBJECT_NAME,OWNER 
FROM DBA_OBJECTS 
WHERE OBJECT_TYPE IN ('PROCEDURE','FUNCTION') 
AND OWNER=iSchema AND STATUS='VALID';



v_est   DEPENDENCY_RESULT_EST_DETAIL%ROWTYPE;


v_effort_1 number;
v_effort_2 number;


BEGIN

IF iRunId is null or iSchema is null then
  Raise_Application_Error (-20001, 'iRunId and iSchema should not be null!!!');
END IF;


    FOR R1 in C1 LOOP

    v_est.NRUNID:= iRunId;
    v_est.schema:=iSchema;
    V_EST.PROC:=R1.OBJECT_NAME;
    v_est.EFFORT_TYPE:=1;-- a Case Migrating a schema to another database

      --LOC
      SELECT COUNT(*) into v_est.LOC from DBA_SOURCE where OWNER=iSchema and name=R1.OBJECT_NAME;
   
      --SELECT  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.ST_COUNT   FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' AND COLUMNNAME!='*';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.SC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='SELECT' AND COLUMNNAME!='*';

      SELECT COUNT(DISTINCT TABLENAME) into v_est.SSC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' AND COLUMNNAME='*';

      --DELETE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DT_COUNT   FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='DELETE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='DELETE';

      --UPDATE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.UT_COUNT   FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='UPDATE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.UC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='UPDATE' ;

      --INSERT  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.IT_COUNT   FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='INSERT';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.IC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='INSERT';
   
      --MERGE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.MT_COUNT   FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='MERGE';
      
      select COUNT(DISTINCT COLUMNNAME) into v_est.MC_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='MERGE';

      --EXECUTE IMMEDIATE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DST_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='EXECUTE IMMEDIATE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DSC_COUNT FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='EXECUTE IMMEDIATE';

      --CURSOR  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DCT_COUNT  FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' ;
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DCC_COUNT FROM (select * from DEPENDENCY_RESULT where owner=iSchema and owner!=tableowner) where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='SELECT';
    
      --EXCEPTIONS   
       SELECT COUNT(*) into v_est.MULEXT_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and MULTIBLEASSIGNMENTEXIST=1;
       SELECT COUNT(*) into v_est.COMPLEX_ASS_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and COMPLEXASSIGNMENTEXIST=1;
       SELECT COUNT(*) into v_est.STRING_CON_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and STRINGCONCATENATIONEXIST=1;
       SELECT COUNT(*) into v_est.NOT_CATCHED_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and TABLENOTCATCHED=1;

    INSERT INTO DEPENDENCY_RESULT_EST_DETAIL VALUES v_est;
    
    END LOOP;


    FOR R1 in C1 LOOP

    v_est.NRUNID:= iRunId;
    v_est.schema:=iSchema;
    V_EST.PROC:=R1.OBJECT_NAME;
    v_est.EFFORT_TYPE:=2;-- b Case Migrating business logic from Data Tier to Application Tier

      --LOC
      SELECT COUNT(*) into v_est.LOC FROM DBA_SOURCE where OWNER=iSchema and name=R1.OBJECT_NAME;
   
      --SELECT  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.ST_COUNT   FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' AND COLUMNNAME!='*';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.SC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='SELECT' AND COLUMNNAME!='*';

      SELECT COUNT(DISTINCT TABLENAME) into v_est.SSC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' AND COLUMNNAME='*';

      --DELETE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DT_COUNT   FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='DELETE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='DELETE';

      --UPDATE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.UT_COUNT   FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='UPDATE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.UC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='UPDATE' ;

      --INSERT  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.IT_COUNT   FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='INSERT';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.IC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='INSERT';
   
      --MERGE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.MT_COUNT   FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='MERGE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.MC_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='MERGE';

      --EXECUTE IMMEDIATE  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DST_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='EXECUTE IMMEDIATE';
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DSC_COUNT FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='EXECUTE IMMEDIATE';

      --CURSOR  
      SELECT COUNT(DISTINCT TABLENAME) into v_est.DCT_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId AND ISEXCEPTION=0 AND  OPERATION='SELECT' ;
      
      SELECT COUNT(DISTINCT COLUMNNAME) into v_est.DCC_COUNT FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and ISEXCEPTION=0 and  OPERATION='SELECT';
    
      --EXCEPTIONS   
       SELECT COUNT(*) into v_est.MULEXT_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and MULTIBLEASSIGNMENTEXIST=1;
       SELECT COUNT(*) into v_est.COMPLEX_ASS_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and COMPLEXASSIGNMENTEXIST=1;
       SELECT COUNT(*) into v_est.STRING_CON_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and STRINGCONCATENATIONEXIST=1;
       SELECT COUNT(*) into v_est.NOT_CATCHED_COUNT  FROM DEPENDENCY_RESULT where OBJECT_NAME = R1.OBJECT_NAME and NRUNID=iRunId and TABLENOTCATCHED=1;

    INSERT INTO DEPENDENCY_RESULT_EST_DETAIL VALUES v_est;
    
    END LOOP;


    SELECT floor(sum(proc_cost)/B1) into v_effort_1
    FROM (select ST_COUNT + MT_COUNT +  IT_COUNT  +  UT_COUNT +  DT_COUNT +  DCT_COUNT +  DST_COUNT + DECODE(MULEXT_COUNT,0,1,MULEXT_COUNT)*DECODE(COMPLEX_ASS_COUNT,0,1,COMPLEX_ASS_COUNT)*DECODE(STRING_CON_COUNT,0,1,STRING_CON_COUNT)*DECODE(NOT_CATCHED_COUNT,0,1,NOT_CATCHED_COUNT) PROC_COST
    FROM DEPENDENCY_RESULT_EST_DETAIL where schema=iSchema and effort_type=1 and nrunid=iRunId) x;
    
    
    SELECT floor(sum(proc_cost)/B2) into v_effort_2
    FROM (select floor((LOC/LC)) + ((ST_COUNT*SC_COUNT)+SSC_COUNT) +  (MT_COUNT*MC_COUNT) +  (IT_COUNT*IC_COUNT)  +  (UT_COUNT*UC_COUNT) +  (DT_COUNT*DC_COUNT) +  (DCT_COUNT*DCC_COUNT) +  (DST_COUNT*DSC_COUNT) + DECODE(MULEXT_COUNT,0,1,MULEXT_COUNT)*DECODE(COMPLEX_ASS_COUNT,0,1,COMPLEX_ASS_COUNT)*DECODE(STRING_CON_COUNT,0,1,STRING_CON_COUNT)*DECODE(NOT_CATCHED_COUNT,0,1,NOT_CATCHED_COUNT) PROC_COST
    FROM DEPENDENCY_RESULT_EST_DETAIL where schema=iSchema and effort_type=2 and nrunid=iRunId) x;


    INSERT INTO DEPENDENCY_RESULT_EST VALUES (iRunId,iSchema,v_effort_1,v_effort_2);



COMMIT;

END;